from __future__ import annotations

__doc__: str
__version__: str

class ECController:
    def __init__(self) -> None: ...
    def is_on_ac(self) -> bool: ...
    def auto_fan_control(self) -> None: ...
    def set_fan_duty(self, duty: int) -> None: ...
    def get_max_temperature(self) -> float: ...
    def get_max_non_battery_temperature(self) -> float: ...