from __future__ import annotations

__doc__: str
__version__: str

def is_on_ac() -> bool: ...
def auto_fan_control() -> None: ...
def set_fan_duty(duty: int) -> None: ...
def get_max_temperature() -> float: ...
def get_max_non_battery_temperature() -> float: ...
